### ISSUE TITLE
Feat: SMS 'sent' successful callback 

### ISSUE THREAD

**Issue by KirstenStake** [moberwasserlechner/capacitor-sms#10]
### Describe the Feature
Provide a successful callback for when the SMS was sent (i.e. the user did not cancel out of the sms journey and they actually pressed the 'send' button)

### Platform(s) Support Requested
- Android
- iOS

### Describe Preferred Solution
- User presses "SEND" button on their sms and this plugin omits a success callback. This is so that an app can, for example, show a 'SMS successfully sent' toast.

### Additional Context
For reference, the same sort of logic regarding this as the cordova-sms-plugin uses

**Comment by jcesarmobile** [comment]
Is this still relevant?
I've not tried to send SMS, but the code seems to resolve once the SMS is sent, so awaiting for the plugin call or using then should not resolve until the SMS is sent and it also has code to reject if some problem happened.
What was not implemented is the cancel error on Android, but I've implemented it on https://github.com/moberwasserlechner/capacitor-sms/pull/22

**Comment by moberwasserlechner** [comment]
Closing this as it does not seem relevant
