### ISSUE TITLE
Feat: Capacitor 3.0 Support

### ISSUE THREAD

**Issue by KirstenStake** [moberwasserlechner/capacitor-sms#11]
### Describe the Feature
The Capacitor 3 RC is out! 🎉 This library should support the new version

### Platform(s) Support Requested

- Android
- iOS

### Describe Preferred Solution
Follow the plugin upgrade guide here: https://capacitorjs.com/docs/v3/updating/plugins/3-0

**Comment by chrum** [comment]
Hey,

I started to upgrade this plugin... its not yet completed but android seems to be workig :)
Will cover iOS soon (hopefully) and then create a PR.

In the meantime... please test android
https://github.com/chrum/capacitor-sms

**Comment by chrum** [comment]
wooho!! PR created #12 
if anyone would like to try it before its merged then you can install it from github:
```bash
npm install https://github.com/chrum/capacitor-sms --save
```

**Comment by playaz87** [comment]
@chrum This package no longer seems to be maintained. Do you plan to publish your fork?

**Comment by moberwasserlechner** [comment]
I'll release a new version in a few days. unfortunately I was extremely busy 😢

**Comment by playaz87** [comment]
> I'll release a new version in a few days. unfortunately I was extremely busy 😢

Thanks, I appreciate you taking time to maintain this public plugin for the community!

**Comment by moberwasserlechner** [comment]
I've release a new version but I would like to ask if you could test it properly as I have no easy way to do it right now. I'll try to push release faster if a PR was merged. thx.

**Comment by playaz87** [comment]
@moberwasserlechner Thanks, I'll test it tomorrow.
