### ISSUE TITLE
Support Capacitor 5

### ISSUE THREAD

**Issue by nerdFrenzs** [moberwasserlechner/capacitor-sms#20]
### Description
Hello
Do you have any plans to support capacitor v5?
### Capacitor version:
Installed Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3
  @capacitor/core: 5.2.3

### Library version:
4.0.0

**Comment by moberwasserlechner** [comment]
Yes. It will be released no later than the end of September. I need this for my own app as well.
