### ISSUE TITLE
Integration with react-native

### ISSUE THREAD

**Issue by Ibeenoch** [moberwasserlechner/capacitor-sms#25]
Please is it possible for this package to be integrated in react native, I really need the package to send SMS programmatically and verified if it was successfully delivered or failed due to insufficient airtime balance, bad cellular network coverage etc, 

If it is possible to integrate with react-native can, you assist me with how it can be configured to achieve this. Thanks

**Comment by moberwasserlechner** [comment]
As react-native is another way to create native apps a CapacitorJS Plugin will not work. You need sth React Native specific afaik.
