### ISSUE TITLE
What is numbers supposed to get? 

### ISSUE THREAD

**Issue by travbus** [moberwasserlechner/capacitor-sms#4]
Using this with a vue.js app 
I did the import
`import { registerWebPlugin } from "@capacitor/core";
import { SmsManager } from "@byteowls/capacitor-sms";`
I registered the plugin when component is created
`created() {
    registerWebPlugin(SmsManager);
}
`
I call this method
`
 Plugins.SmsManager.send({
        numbers: ["749093246"],
        text: "test test"
      })
        .then(() => {
          // SMS app was opened
        })
        .catch(error => {
          // see error codes below
          if (error.message !== "SEND_CANCELLED") {
            // show toast with error message
            // eslint-disable-next-line
            console.log(error.message);
          }
        });`

Getting error in xcode
`SmsManager   
send   
72688974   
ERROR MESSAGE:    
{"message":"ERR_NO_NUMBERS","errorMessage":""}   
⚡️  [log] - ERR_NO_NUMBERS   `

How is numbers formatted? I've tried all 3 ways
 [749093246],  or ["749093246"], "749093246" ?? 

This plugin only opens sms right? User still has to send the sms?

**Comment by moberwasserlechner** [comment]
>This plugin only opens sms right? User still has to send the sms?
yes and yes.

Are you sure that you use a valid number?

**Comment by moberwasserlechner** [comment]
I'm closing this as the author did not answer my followup question. Please create a new issue if the problem persists.
