### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by mdshadman** [moberwasserlechner/capacitor-sms#5]
After following and implementing android flow I am getting undefined in response when i am calling SendSMS function.
```
SendSMS() { 
            Plugins.SmsManager.send({
                numbers: ['7014859919'],
                text: 'Hi shadman how are you?',
            }).then(() => {
                // SMS app was opened
            }).catch((error: any) => {
                // see error codes below
                if (error.message !== "SEND_CANCELLED") {
                    // show toast with error message
                    console.log(error.message);
                }
            });
 
    }
```

**Comment by moberwasserlechner** [comment]
Be aware that this plugin does not send anything. I just opens the SMS app (if there is any).

See https://github.com/moberwasserlechner/capacitor-sms#use-it

**Comment by moberwasserlechner** [comment]
>I am getting undefined in response when i am calling SendSMS function.

I did not define any return value in your function. This is nothing the plugin can handle for you.
