### ISSUE TITLE
cannot find symbol (Android)

### ISSUE THREAD

**Issue by asiermusa** [moberwasserlechner/capacitor-sms#8]
Hi!

when I try to build my app in Android Sudio I get this error message: 
_error: cannot find symbol add(SmsManagerPlugin.class)_

I think that I've to import the class but in the documentation doesn't say nothing about that. Can you help me?

**Comment by moberwasserlechner** [comment]
Hi, 

as a Java developer I did thought leaving that from the docs might be a problem.

You have a few possibilities:
1) You just need press ALT + Enter when the cursor is in the class name in Android Studio. It will import the class automatically
2) Add `import com.byteowls.capacitor.sms.SmsManagerPlugin;` to imports sections of class
3) Use the full qualified name `add( com.byteowls.capacitor.sms.SmsManagerPlugin)`

I adapted the docs to address that.
